Repository halo-sigs/plugin-highlightjs, pull requests merged in 2023-06, with the labels that each got.

#5 perf: add defer attribute for script
  src/main/java/run/halo/highlightjs/HighlightJSHeadProcessor.java
Labels: release-note-none, kind/improvement, approved

#7 chore: bump halo plugin devtools version
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  lib/halo-2.0.0-SNAPSHOT-plain.jar
  settings.gradle
  src/main/java/run/halo/highlightjs/HighlightJSHeadProcessor.java
Labels: release-note-none, lgtm, kind/improvement, approved

#8 feat: support page matching to use code highlighting
  src/main/java/run/halo/highlightjs/HighlightJSHeadProcessor.java
  src/main/resources/extensions/settings.yaml
Labels: kind/feature, release-note, lgtm, approved
