Repository halo-sigs/plugin-highlightjs, pull requests merged in 2024-09, with the labels that each got.

#26 chore: bump rspack version
  build.gradle
  ui/package.json
  ui/pnpm-lock.yaml
  ui/rspack.config.mjs
Labels: release-note-none, lgtm, approved

#27 Fix incorrect issues and repo links
  src/main/resources/plugin.yaml
Labels: kind/documentation, release-note-none, approved

#28 feat: improve compatibility of the copy code feature
  src/main/java/run/halo/highlightjs/HighlightJSHeadProcessor.java
  src/main/resources/static/plugins/highlightjs-copy.css
  src/main/resources/static/plugins/highlightjs-copy.js
  src/main/resources/static/plugins/highlightjs-copy.min.css
  src/main/resources/static/plugins/highlightjs-copy.min.js
Labels: release-note, lgtm, approved

#29 feat: add plugin version param for static resources
  src/main/java/run/halo/highlightjs/HighlightJSHeadProcessor.java
Labels: kind/feature, release-note, lgtm, approved

#31 fix: resolve style compatibility issues for the copy button
  src/main/resources/static/plugins/highlightjs-copy.css
Labels: kind/bug, release-note, lgtm, approved
